In [1]:
#NumPy Array
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
 my_mat = [[1,2,3],[4,5,6],[6,7,8]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [14]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
np.random.rand(5)

array([ 0.54435361,  0.21946791,  0.6281583 ,  0.03959544,  0.72528873])

In [17]:
np.random.rand(5,5)

array([[ 0.09375052,  0.32877298,  0.42616842,  0.75147314,  0.52117639],
       [ 0.96776952,  0.57932054,  0.17839445,  0.01232894,  0.38658996],
       [ 0.87779265,  0.1104657 ,  0.75528535,  0.80768113,  0.45059976],
       [ 0.10325606,  0.63817604,  0.54684795,  0.01008906,  0.6051725 ],
       [ 0.6371155 ,  0.40921612,  0.54684061,  0.44633548,  0.09380325]])

In [18]:
np.random.randn(2)

array([-0.63064497, -3.01469239])

In [19]:
np.random.randint(1,100)

31

In [20]:
np.random.randint(1,100,10)

array([62, 68, 16, 94, 20, 12, 66, 53, 79, 80])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)

In [24]:
ranarr

array([11, 10, 30, 33, 29, 38, 33, 25, 33, 43])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr.max()

43

In [29]:
ranarr.min()


10

In [30]:
ranarr

array([11, 10, 30, 33, 29, 38, 33, 25, 33, 43])

In [31]:
ranarr.argmax()


9

In [32]:
ranarr.argmin()

1

In [33]:
arr.shape

(25L,)

In [36]:
arr = arr.reshape(5,5)

In [37]:
arr.shape

(5L, 5L)

In [38]:
arr.dtype

dtype('int32')

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

4

## NumPy Indexing and Selection

In [41]:
import numpy as np

In [42]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[8]

8

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [47]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[0:5] = 100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:6]

In [53]:
slice_of_arr


array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:] = 99

In [55]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy = arr.copy()

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy[:] = 100

In [61]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [64]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
arr_2d[1][1]

25

In [66]:
arr_2d[2,1]

40

In [67]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [72]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [73]:
arr = np.arange(1,11)

In [74]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
bool_arr = arr>5

In [77]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [78]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [81]:
arr[arr==7]

array([7])

In [82]:
arr_2d = np.arange(50).reshape(5,10)

In [83]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [85]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# NumPy Operations

In [86]:
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [89]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [91]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [92]:
1/0

ZeroDivisionError: integer division or modulo by zero

In [93]:
arr / arr

C:\Users\SATISH\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [94]:
1 / arr

C:\Users\SATISH\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [96]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [97]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [98]:
np.max(arr)

10

In [99]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [100]:
np.log(arr)

C:\Users\SATISH\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])